const fs = require('fs');
const path = require('path');

// 背景画像ディレクトリのパス
const imagesDir = path.join(__dirname, '../public/images');

// 画像ファイルの拡張子
const imageExtensions = ['.jpg', '.jpeg', '.png'];

// ディレクトリ内の画像ファイルを取得
function getImageFiles() {
  try {
    const files = fs.readdirSync(imagesDir);
    return files.filter(file => {
      const ext = path.extname(file).toLowerCase();
      return imageExtensions.includes(ext);
    }).sort();
  } catch (error) {
    console.error('Error reading images directory:', error);
    return [];
  }
}

// backgroundImages.tsを生成
function updateConfig() {
  const imageFiles = getImageFiles();
  
  if (imageFiles.length === 0) {
    console.error('No image files found in public/images/');
    process.exit(1);
  }
  
  console.log(`Found ${imageFiles.length} image files:`, imageFiles);
  
  // backgroundImages.tsに出力
  const outputPath = path.join(__dirname, '../src/data/backgroundImages.ts');
  
  const content = `// This file is auto-generated by update-images.js
// Contains list of background images

export const BACKGROUND_IMAGES = [
${imageFiles.map(file => `  '${file}'`).join(',\n')}
] as const;`;
  
  fs.writeFileSync(outputPath, content);
  
  console.log('Generated src/data/backgroundImages.ts with new image list');
}

updateConfig();